qodana_task:
  name: Qodana
  container:
    image: jetbrains/qodana:latest
  env:
    CIRRUS_WORKING_DIR: /data/project
  generate_report_script:
    - /opt/idea/bin/entrypoint --save-report --report-dir=report
  always:
    results_artifacts:
      path: "report/results/result-allProblems.json"
      format: qodana

poetry_task:
    container:
        image: python:slim
    setup_script:
        - apt-get update -y
        - apt-get install -y --no-install-recommends strace poppler-utils software-properties-common build-essential make gcc g++ libmagic-dev
        - pip install -U pip setuptools wheel tox tox-gh-actions poetry
    install_script:
        - poetry install
    test_script:
        - poetry run make lint
        - poetry run make test

tox_task:
    container:
        image: python:slim
    setup_script:
        - apt-get update -y
        - apt-get install -y --no-install-recommends strace poppler-utils software-properties-common build-essential make gcc g++ libmagic-dev
        - pip install -U pip setuptools wheel tox tox-gh-actions poetry
    test_script:
        - tox
