# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Abilian SBE - An open source collaborative platform for business applications
theme:
  name: material
