version = 1
SPDX-PackageName = "abilian-sbe"
SPDX-PackageSupplier = "Abilian SAS <contact@abilian.com>"
SPDX-PackageDownloadLocation = "https://github.com/abilian/abilian-sbe-monorepo"

[[annotations]]
path = ["**/*.py", "**/Makefile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2024 Abilian SAS <contact@abilian.com>"
SPDX-License-Identifier = "LGPL-3.0-only"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2024 Abilian SAS <contact@abilian.com>"
SPDX-License-Identifier = "LGPL-3.0-only"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."

[[annotations]]
path = ["DCO.txt", "CODE_OF_CONDUCT.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2024 Abilian SAS <contact@abilian.com>"
SPDX-License-Identifier = "CC0-1.0"


# TODO: not working yet
#[[annotations]]
#path = ["*/src/**"]
#precedence = "aggregate"
#SPDX-FileCopyrightText = "2023-2024 Abilian SAS <contact@abilian.com>"
#SPDX-License-Identifier = "AGPL-3.0-only"
#SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."

[[annotations]]
path = ["apps/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2024 Abilian SAS <contact@abilian.com>"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."

[[annotations]]
path = ["docs/**", "notes/**", "*.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2024 Abilian SAS <contact@abilian.com>"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."
