image: ubuntu/24.04

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  # Python
  - python3-dev
  - python3-pip
  - python3-wheel
  - tox
  # Node
  - nodejs
  - npm
  # Libraries
  - libpq-dev
  - libxslt-dev
  - libxslt1-dev
  - libjpeg-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev
  - libmagic-dev
  - libjpeg-turbo8-dev
  - libnode-dev
  # Other deps
  - strace
  - poppler-utils
  - libreoffice
  - default-jdk-headless
  - curl

tasks:
  - setup: |
      sudo apt-get install pipx
      pipx install uv nox
      cd abilian-sbe
      npm install

  - lint-nox: |
      cd abilian-sbe
      nox -e lint

  - test-nox: |
      cd abilian-sbe
      # TODO: install other versions using rye
      nox -e pytest-3.10

triggers:
  - action: email
    condition: failure
    to: builds@fermigier.com
