# Copyright (c) 2024, Abilian SAS
#
# SPDX-License-Identifier: BSD-3-Clause

image: ubuntu/24.04

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  # Python 3.12
  - python3-dev
  - python3-pip
  - python3-wheel
  - pipx
  # Node
  - nodejs
  - npm
  - libnode-dev
  # Librairies for DB connectors
  - libsqlite3-dev
  - libpq-dev
  - libmariadb-dev
  # More libraries
  - libbz2-dev
  - libffi-dev
  - libjpeg-dev
  - libjpeg-turbo8-dev
  - libmagic-dev
  - libxslt-dev
  - libxslt1-dev
  # Other deps
  - strace
  - poppler-utils
  - libreoffice
  - default-jdk-headless
  - curl

tasks:
  - setup: |
      sudo pip install --break-system-packages -U uv nox
      cd abilian-sbe
      npm install

  - lint-nox: |
      cd abilian-sbe
      nox -e lint

  - test-nox: |
      cd abilian-sbe
      # Default Python version is python 3.12
      # TODO: install other versions using rye or uv
      nox -e pytest-3.12

triggers:
  - action: email
    condition: failure
    to: builds@fermigier.com
