# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

#  abilian-sbe:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
